spring:
  application:
    name: inventory-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_secret_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  cloud:
    stream:
      function:
#        definition: orderPurchaseEventProcess
      bindings:
        paymentsEventIn:
          destination: payments
          content-type: application/json
        deliveryEventOut:
          destination: delivery
          content-type: application/json
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
#        consumer:
#          group-id: order-consumer-group
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true

server:
  port: 8099

